// Code generated by ojson generator. DO NOT EDIT.
package openai

import oj "../../../pkgs/ojson/jsonimpl"

// Unmarshals JSON into OpenAI_Tool_Function
// Source: openai (src/providers/openai/types.odin)
unmarshal_open_ai_tool_function :: proc(r: ^oj.Reader, path: string = "") -> (result: OpenAI_Tool_Function, err: oj.Error) {
	elem, elem_err := oj.element_at(r, path)
	if elem_err != .OK do return result, elem_err
	return unmarshal_open_ai_tool_function_elem(r, elem)
}

// Unmarshals JSON element into OpenAI_Tool_Function
unmarshal_open_ai_tool_function_elem :: proc(r: ^oj.Reader, elem: oj.Element) -> (result: OpenAI_Tool_Function, err: oj.Error) {
	result.name, err = oj.read_string_elem(r, elem, "name")
	if err != .OK && err != .Key_Not_Found && err != .Type_Mismatch do return

	result.arguments, err = oj.read_string_elem(r, elem, "arguments")
	if err != .OK && err != .Key_Not_Found && err != .Type_Mismatch do return

	return
}

is_zero_open_ai_tool_function :: proc(v: OpenAI_Tool_Function) -> bool {
	return v.name == "" && v.arguments == ""
}

// Marshals OpenAI_Tool_Function to JSON
marshal_open_ai_tool_function :: proc(w: ^oj.Writer, value: OpenAI_Tool_Function) {
	oj.write_object_start(w)
	oj.write_key(w, "name")
	oj.write_string(w, value.name)
	oj.write_key(w, "arguments")
	oj.write_string(w, value.arguments)
	oj.write_object_end(w)
}

// Unmarshals JSON into OpenAI_Tool_Call
// Source: openai (src/providers/openai/types.odin)
unmarshal_open_ai_tool_call :: proc(r: ^oj.Reader, path: string = "") -> (result: OpenAI_Tool_Call, err: oj.Error) {
	elem, elem_err := oj.element_at(r, path)
	if elem_err != .OK do return result, elem_err
	return unmarshal_open_ai_tool_call_elem(r, elem)
}

// Unmarshals JSON element into OpenAI_Tool_Call
unmarshal_open_ai_tool_call_elem :: proc(r: ^oj.Reader, elem: oj.Element) -> (result: OpenAI_Tool_Call, err: oj.Error) {
	result.id, err = oj.read_string_elem(r, elem, "id")
	if err != .OK && err != .Key_Not_Found && err != .Type_Mismatch do return

	result.type, err = oj.read_string_elem(r, elem, "type")
	if err != .OK && err != .Key_Not_Found && err != .Type_Mismatch do return

	{
		nested_elem, nested_err := oj.obj_element_from(r, elem, "function")
		if nested_err == .OK {
			result.function, err = unmarshal_open_ai_tool_function_elem(r, nested_elem)
			if err != .OK do return
		}
	}

	return
}

is_zero_open_ai_tool_call :: proc(v: OpenAI_Tool_Call) -> bool {
	return v.id == "" && v.type == "" && is_zero_open_ai_tool_function(v.function)
}

// Marshals OpenAI_Tool_Call to JSON
marshal_open_ai_tool_call :: proc(w: ^oj.Writer, value: OpenAI_Tool_Call) {
	oj.write_object_start(w)
	oj.write_key(w, "id")
	oj.write_string(w, value.id)
	oj.write_key(w, "type")
	oj.write_string(w, value.type)
	oj.write_key(w, "function")
	marshal_open_ai_tool_function(w, value.function)
	oj.write_object_end(w)
}

// Unmarshals JSON into OpenAI_Message
// Source: openai (src/providers/openai/types.odin)
unmarshal_open_ai_message :: proc(r: ^oj.Reader, path: string = "") -> (result: OpenAI_Message, err: oj.Error) {
	elem, elem_err := oj.element_at(r, path)
	if elem_err != .OK do return result, elem_err
	return unmarshal_open_ai_message_elem(r, elem)
}

// Unmarshals JSON element into OpenAI_Message
unmarshal_open_ai_message_elem :: proc(r: ^oj.Reader, elem: oj.Element) -> (result: OpenAI_Message, err: oj.Error) {
	result.role, err = oj.read_string_elem(r, elem, "role")
	if err != .OK && err != .Key_Not_Found && err != .Type_Mismatch do return

	result.content, err = oj.read_string_elem(r, elem, "content")
	if err != .OK && err != .Key_Not_Found && err != .Type_Mismatch do return

	result.tool_call_id, err = oj.read_string_elem(r, elem, "tool_call_id")
	if err != .OK && err != .Key_Not_Found && err != .Type_Mismatch do return

	{
		arr_elem, arr_err := oj.obj_element_from(r, elem, "tool_calls")
		if arr_err == .OK {
			items, _ := oj.array_elements_from(r, arr_elem)
			result.tool_calls = make([]OpenAI_Tool_Call, len(items))
			for item_elem, i in items {
				result.tool_calls[i], err = unmarshal_open_ai_tool_call_elem(r, item_elem)
				if err != .OK do return
			}
		}
	}

	return
}

is_zero_open_ai_message :: proc(v: OpenAI_Message) -> bool {
	return v.role == "" && v.content == "" && v.tool_call_id == "" && len(v.tool_calls) == 0
}

// Marshals OpenAI_Message to JSON
marshal_open_ai_message :: proc(w: ^oj.Writer, value: OpenAI_Message) {
	oj.write_object_start(w)
	oj.write_key(w, "role")
	oj.write_string(w, value.role)
	oj.write_key(w, "content")
	oj.write_string(w, value.content)
	if value.tool_call_id != "" {
		oj.write_key(w, "tool_call_id")
		oj.write_string(w, value.tool_call_id)
	}
	if len(value.tool_calls) > 0 {
		oj.write_key(w, "tool_calls")
	oj.write_array_start(w)
	for item in value.tool_calls {
		marshal_open_ai_tool_call(w, item)
	}
	oj.write_array_end(w)
	}
	oj.write_object_end(w)
}

// Unmarshals JSON into OpenAI_Tool_Def_Function
// Source: openai (src/providers/openai/types.odin)
unmarshal_open_ai_tool_def_function :: proc(r: ^oj.Reader, path: string = "") -> (result: OpenAI_Tool_Def_Function, err: oj.Error) {
	elem, elem_err := oj.element_at(r, path)
	if elem_err != .OK do return result, elem_err
	return unmarshal_open_ai_tool_def_function_elem(r, elem)
}

// Unmarshals JSON element into OpenAI_Tool_Def_Function
unmarshal_open_ai_tool_def_function_elem :: proc(r: ^oj.Reader, elem: oj.Element) -> (result: OpenAI_Tool_Def_Function, err: oj.Error) {
	result.name, err = oj.read_string_elem(r, elem, "name")
	if err != .OK && err != .Key_Not_Found && err != .Type_Mismatch do return

	result.description, err = oj.read_string_elem(r, elem, "description")
	if err != .OK && err != .Key_Not_Found && err != .Type_Mismatch do return

	{
		raw_val, raw_err := oj.read_raw_elem(r, elem, "parameters")
		if raw_err != .OK && raw_err != .Key_Not_Found && raw_err != .Type_Mismatch do return result, raw_err
		if raw_err == .OK do result.parameters = raw_val
	}

	return
}

is_zero_open_ai_tool_def_function :: proc(v: OpenAI_Tool_Def_Function) -> bool {
	return v.name == "" && v.description == "" && v.parameters == ""
}

// Marshals OpenAI_Tool_Def_Function to JSON
marshal_open_ai_tool_def_function :: proc(w: ^oj.Writer, value: OpenAI_Tool_Def_Function) {
	oj.write_object_start(w)
	oj.write_key(w, "name")
	oj.write_string(w, value.name)
	oj.write_key(w, "description")
	oj.write_string(w, value.description)
	oj.write_key(w, "parameters")
	oj.write_raw(w, value.parameters)
	oj.write_object_end(w)
}

// Unmarshals JSON into OpenAI_Tool_Def
// Source: openai (src/providers/openai/types.odin)
unmarshal_open_ai_tool_def :: proc(r: ^oj.Reader, path: string = "") -> (result: OpenAI_Tool_Def, err: oj.Error) {
	elem, elem_err := oj.element_at(r, path)
	if elem_err != .OK do return result, elem_err
	return unmarshal_open_ai_tool_def_elem(r, elem)
}

// Unmarshals JSON element into OpenAI_Tool_Def
unmarshal_open_ai_tool_def_elem :: proc(r: ^oj.Reader, elem: oj.Element) -> (result: OpenAI_Tool_Def, err: oj.Error) {
	result.type, err = oj.read_string_elem(r, elem, "type")
	if err != .OK && err != .Key_Not_Found && err != .Type_Mismatch do return

	{
		nested_elem, nested_err := oj.obj_element_from(r, elem, "function")
		if nested_err == .OK {
			result.function, err = unmarshal_open_ai_tool_def_function_elem(r, nested_elem)
			if err != .OK do return
		}
	}

	return
}

is_zero_open_ai_tool_def :: proc(v: OpenAI_Tool_Def) -> bool {
	return v.type == "" && is_zero_open_ai_tool_def_function(v.function)
}

// Marshals OpenAI_Tool_Def to JSON
marshal_open_ai_tool_def :: proc(w: ^oj.Writer, value: OpenAI_Tool_Def) {
	oj.write_object_start(w)
	oj.write_key(w, "type")
	oj.write_string(w, value.type)
	oj.write_key(w, "function")
	marshal_open_ai_tool_def_function(w, value.function)
	oj.write_object_end(w)
}

// Unmarshals JSON into OpenAI_Request
// Source: openai (src/providers/openai/types.odin)
unmarshal_open_ai_request :: proc(r: ^oj.Reader, path: string = "") -> (result: OpenAI_Request, err: oj.Error) {
	elem, elem_err := oj.element_at(r, path)
	if elem_err != .OK do return result, elem_err
	return unmarshal_open_ai_request_elem(r, elem)
}

// Unmarshals JSON element into OpenAI_Request
unmarshal_open_ai_request_elem :: proc(r: ^oj.Reader, elem: oj.Element) -> (result: OpenAI_Request, err: oj.Error) {
	result.model, err = oj.read_string_elem(r, elem, "model")
	if err != .OK && err != .Key_Not_Found && err != .Type_Mismatch do return

	{
		val: f64
		val, err = oj.read_f64_elem(r, elem, "temperature")
		if err != .OK && err != .Key_Not_Found && err != .Type_Mismatch do return
		if err == .OK do result.temperature = f32(val)
	}

	result.max_tokens, err = oj.read_int_elem(r, elem, "max_tokens")
	if err != .OK && err != .Key_Not_Found && err != .Type_Mismatch do return

	result.stream, err = oj.read_bool_elem(r, elem, "stream")
	if err != .OK && err != .Key_Not_Found && err != .Type_Mismatch do return

	{
		arr_elem, arr_err := oj.obj_element_from(r, elem, "messages")
		if arr_err == .OK {
			items, _ := oj.array_elements_from(r, arr_elem)
			result.messages = make([]OpenAI_Message, len(items))
			for item_elem, i in items {
				result.messages[i], err = unmarshal_open_ai_message_elem(r, item_elem)
				if err != .OK do return
			}
		}
	}

	{
		arr_elem, arr_err := oj.obj_element_from(r, elem, "tools")
		if arr_err == .OK {
			items, _ := oj.array_elements_from(r, arr_elem)
			result.tools = make([]OpenAI_Tool_Def, len(items))
			for item_elem, i in items {
				result.tools[i], err = unmarshal_open_ai_tool_def_elem(r, item_elem)
				if err != .OK do return
			}
		}
	}

	return
}

is_zero_open_ai_request :: proc(v: OpenAI_Request) -> bool {
	return v.model == "" && v.temperature == 0 && v.max_tokens == 0 && !v.stream && len(v.messages) == 0 && len(v.tools) == 0
}

// Marshals OpenAI_Request to JSON
marshal_open_ai_request :: proc(w: ^oj.Writer, value: OpenAI_Request) {
	oj.write_object_start(w)
	oj.write_key(w, "model")
	oj.write_string(w, value.model)
	oj.write_key(w, "temperature")
	oj.write_f32(w, value.temperature)
	oj.write_key(w, "max_tokens")
	oj.write_int(w, value.max_tokens)
	if value.stream {
		oj.write_key(w, "stream")
		oj.write_bool(w, value.stream)
	}
	oj.write_key(w, "messages")
	oj.write_array_start(w)
	for item in value.messages {
		marshal_open_ai_message(w, item)
	}
	oj.write_array_end(w)
	if len(value.tools) > 0 {
		oj.write_key(w, "tools")
	oj.write_array_start(w)
	for item in value.tools {
		marshal_open_ai_tool_def(w, item)
	}
	oj.write_array_end(w)
	}
	oj.write_object_end(w)
}

// Unmarshals JSON into OpenAI_Response_Choice
// Source: openai (src/providers/openai/types.odin)
unmarshal_open_ai_response_choice :: proc(r: ^oj.Reader, path: string = "") -> (result: OpenAI_Response_Choice, err: oj.Error) {
	elem, elem_err := oj.element_at(r, path)
	if elem_err != .OK do return result, elem_err
	return unmarshal_open_ai_response_choice_elem(r, elem)
}

// Unmarshals JSON element into OpenAI_Response_Choice
unmarshal_open_ai_response_choice_elem :: proc(r: ^oj.Reader, elem: oj.Element) -> (result: OpenAI_Response_Choice, err: oj.Error) {
	result.finish_reason, err = oj.read_string_elem(r, elem, "finish_reason")
	if err != .OK && err != .Key_Not_Found && err != .Type_Mismatch do return

	{
		nested_elem, nested_err := oj.obj_element_from(r, elem, "message")
		if nested_err == .OK {
			result.message, err = unmarshal_open_ai_message_elem(r, nested_elem)
			if err != .OK do return
		}
	}

	return
}

is_zero_open_ai_response_choice :: proc(v: OpenAI_Response_Choice) -> bool {
	return v.finish_reason == "" && is_zero_open_ai_message(v.message)
}

// Marshals OpenAI_Response_Choice to JSON
marshal_open_ai_response_choice :: proc(w: ^oj.Writer, value: OpenAI_Response_Choice) {
	oj.write_object_start(w)
	oj.write_key(w, "finish_reason")
	oj.write_string(w, value.finish_reason)
	oj.write_key(w, "message")
	marshal_open_ai_message(w, value.message)
	oj.write_object_end(w)
}

// Unmarshals JSON into OpenAI_Usage
// Source: openai (src/providers/openai/types.odin)
unmarshal_open_ai_usage :: proc(r: ^oj.Reader, path: string = "") -> (result: OpenAI_Usage, err: oj.Error) {
	elem, elem_err := oj.element_at(r, path)
	if elem_err != .OK do return result, elem_err
	return unmarshal_open_ai_usage_elem(r, elem)
}

// Unmarshals JSON element into OpenAI_Usage
unmarshal_open_ai_usage_elem :: proc(r: ^oj.Reader, elem: oj.Element) -> (result: OpenAI_Usage, err: oj.Error) {
	result.prompt_tokens, err = oj.read_int_elem(r, elem, "prompt_tokens")
	if err != .OK && err != .Key_Not_Found && err != .Type_Mismatch do return

	result.completion_tokens, err = oj.read_int_elem(r, elem, "completion_tokens")
	if err != .OK && err != .Key_Not_Found && err != .Type_Mismatch do return

	return
}

is_zero_open_ai_usage :: proc(v: OpenAI_Usage) -> bool {
	return v.prompt_tokens == 0 && v.completion_tokens == 0
}

// Marshals OpenAI_Usage to JSON
marshal_open_ai_usage :: proc(w: ^oj.Writer, value: OpenAI_Usage) {
	oj.write_object_start(w)
	oj.write_key(w, "prompt_tokens")
	oj.write_int(w, value.prompt_tokens)
	oj.write_key(w, "completion_tokens")
	oj.write_int(w, value.completion_tokens)
	oj.write_object_end(w)
}

// Unmarshals JSON into OpenAI_Response
// Source: openai (src/providers/openai/types.odin)
unmarshal_open_ai_response :: proc(r: ^oj.Reader, path: string = "") -> (result: OpenAI_Response, err: oj.Error) {
	elem, elem_err := oj.element_at(r, path)
	if elem_err != .OK do return result, elem_err
	return unmarshal_open_ai_response_elem(r, elem)
}

// Unmarshals JSON element into OpenAI_Response
unmarshal_open_ai_response_elem :: proc(r: ^oj.Reader, elem: oj.Element) -> (result: OpenAI_Response, err: oj.Error) {
	{
		arr_elem, arr_err := oj.obj_element_from(r, elem, "choices")
		if arr_err == .OK {
			items, _ := oj.array_elements_from(r, arr_elem)
			result.choices = make([]OpenAI_Response_Choice, len(items))
			for item_elem, i in items {
				result.choices[i], err = unmarshal_open_ai_response_choice_elem(r, item_elem)
				if err != .OK do return
			}
		}
	}

	{
		nested_elem, nested_err := oj.obj_element_from(r, elem, "usage")
		if nested_err == .OK {
			result.usage, err = unmarshal_open_ai_usage_elem(r, nested_elem)
			if err != .OK do return
		}
	}

	return
}

is_zero_open_ai_response :: proc(v: OpenAI_Response) -> bool {
	return len(v.choices) == 0 && is_zero_open_ai_usage(v.usage)
}

// Marshals OpenAI_Response to JSON
marshal_open_ai_response :: proc(w: ^oj.Writer, value: OpenAI_Response) {
	oj.write_object_start(w)
	oj.write_key(w, "choices")
	oj.write_array_start(w)
	for item in value.choices {
		marshal_open_ai_response_choice(w, item)
	}
	oj.write_array_end(w)
	oj.write_key(w, "usage")
	marshal_open_ai_usage(w, value.usage)
	oj.write_object_end(w)
}
