// Code generated by ojson generator. DO NOT EDIT.
package gemini

import oj "../../../pkgs/ojson/jsonimpl"

// Unmarshals JSON into Gemini_Function_Call
// Source: gemini (src/providers/gemini/types.odin)
unmarshal_gemini_function_call :: proc(r: ^oj.Reader, path: string = "") -> (result: Gemini_Function_Call, err: oj.Error) {
	elem, elem_err := oj.element_at(r, path)
	if elem_err != .OK do return result, elem_err
	return unmarshal_gemini_function_call_elem(r, elem)
}

// Unmarshals JSON element into Gemini_Function_Call
unmarshal_gemini_function_call_elem :: proc(r: ^oj.Reader, elem: oj.Element) -> (result: Gemini_Function_Call, err: oj.Error) {
	result.name, err = oj.read_string_elem(r, elem, "name")
	if err != .OK && err != .Key_Not_Found && err != .Type_Mismatch do return

	{
		raw_val, raw_err := oj.read_raw_elem(r, elem, "args")
		if raw_err != .OK && raw_err != .Key_Not_Found && raw_err != .Type_Mismatch do return result, raw_err
		if raw_err == .OK do result.args = raw_val
	}

	return
}

is_zero_gemini_function_call :: proc(v: Gemini_Function_Call) -> bool {
	return v.name == "" && v.args == ""
}

// Marshals Gemini_Function_Call to JSON
marshal_gemini_function_call :: proc(w: ^oj.Writer, value: Gemini_Function_Call) {
	oj.write_object_start(w)
	oj.write_key(w, "name")
	oj.write_string(w, value.name)
	oj.write_key(w, "args")
	oj.write_raw(w, value.args)
	oj.write_object_end(w)
}

// Unmarshals JSON into Gemini_Function_Response_Body
// Source: gemini (src/providers/gemini/types.odin)
unmarshal_gemini_function_response_body :: proc(r: ^oj.Reader, path: string = "") -> (result: Gemini_Function_Response_Body, err: oj.Error) {
	elem, elem_err := oj.element_at(r, path)
	if elem_err != .OK do return result, elem_err
	return unmarshal_gemini_function_response_body_elem(r, elem)
}

// Unmarshals JSON element into Gemini_Function_Response_Body
unmarshal_gemini_function_response_body_elem :: proc(r: ^oj.Reader, elem: oj.Element) -> (result: Gemini_Function_Response_Body, err: oj.Error) {
	result.result, err = oj.read_string_elem(r, elem, "result")
	if err != .OK && err != .Key_Not_Found && err != .Type_Mismatch do return

	return
}

is_zero_gemini_function_response_body :: proc(v: Gemini_Function_Response_Body) -> bool {
	return v.result == ""
}

// Marshals Gemini_Function_Response_Body to JSON
marshal_gemini_function_response_body :: proc(w: ^oj.Writer, value: Gemini_Function_Response_Body) {
	oj.write_object_start(w)
	oj.write_key(w, "result")
	oj.write_string(w, value.result)
	oj.write_object_end(w)
}

// Unmarshals JSON into Gemini_Function_Response
// Source: gemini (src/providers/gemini/types.odin)
unmarshal_gemini_function_response :: proc(r: ^oj.Reader, path: string = "") -> (result: Gemini_Function_Response, err: oj.Error) {
	elem, elem_err := oj.element_at(r, path)
	if elem_err != .OK do return result, elem_err
	return unmarshal_gemini_function_response_elem(r, elem)
}

// Unmarshals JSON element into Gemini_Function_Response
unmarshal_gemini_function_response_elem :: proc(r: ^oj.Reader, elem: oj.Element) -> (result: Gemini_Function_Response, err: oj.Error) {
	result.name, err = oj.read_string_elem(r, elem, "name")
	if err != .OK && err != .Key_Not_Found && err != .Type_Mismatch do return

	{
		nested_elem, nested_err := oj.obj_element_from(r, elem, "response")
		if nested_err == .OK {
			result.response, err = unmarshal_gemini_function_response_body_elem(r, nested_elem)
			if err != .OK do return
		}
	}

	return
}

is_zero_gemini_function_response :: proc(v: Gemini_Function_Response) -> bool {
	return v.name == "" && is_zero_gemini_function_response_body(v.response)
}

// Marshals Gemini_Function_Response to JSON
marshal_gemini_function_response :: proc(w: ^oj.Writer, value: Gemini_Function_Response) {
	oj.write_object_start(w)
	oj.write_key(w, "name")
	oj.write_string(w, value.name)
	oj.write_key(w, "response")
	marshal_gemini_function_response_body(w, value.response)
	oj.write_object_end(w)
}

// Unmarshals JSON into Gemini_Part
// Source: gemini (src/providers/gemini/types.odin)
unmarshal_gemini_part :: proc(r: ^oj.Reader, path: string = "") -> (result: Gemini_Part, err: oj.Error) {
	elem, elem_err := oj.element_at(r, path)
	if elem_err != .OK do return result, elem_err
	return unmarshal_gemini_part_elem(r, elem)
}

// Unmarshals JSON element into Gemini_Part
unmarshal_gemini_part_elem :: proc(r: ^oj.Reader, elem: oj.Element) -> (result: Gemini_Part, err: oj.Error) {
	result.text, err = oj.read_string_elem(r, elem, "text")
	if err != .OK && err != .Key_Not_Found && err != .Type_Mismatch do return

	result.thought, err = oj.read_bool_elem(r, elem, "thought")
	if err != .OK && err != .Key_Not_Found && err != .Type_Mismatch do return

	{
		nested_elem, nested_err := oj.obj_element_from(r, elem, "functionCall")
		if nested_err == .OK {
			result.function_call, err = unmarshal_gemini_function_call_elem(r, nested_elem)
			if err != .OK do return
		}
	}

	{
		nested_elem, nested_err := oj.obj_element_from(r, elem, "functionResponse")
		if nested_err == .OK {
			result.function_response, err = unmarshal_gemini_function_response_elem(r, nested_elem)
			if err != .OK do return
		}
	}

	return
}

is_zero_gemini_part :: proc(v: Gemini_Part) -> bool {
	return v.text == "" && !v.thought && is_zero_gemini_function_call(v.function_call) && is_zero_gemini_function_response(v.function_response)
}

// Marshals Gemini_Part to JSON
marshal_gemini_part :: proc(w: ^oj.Writer, value: Gemini_Part) {
	oj.write_object_start(w)
	if value.text != "" {
		oj.write_key(w, "text")
		oj.write_string(w, value.text)
	}
	if value.thought {
		oj.write_key(w, "thought")
		oj.write_bool(w, value.thought)
	}
	if !is_zero_gemini_function_call(value.function_call) {
		oj.write_key(w, "functionCall")
		marshal_gemini_function_call(w, value.function_call)
	}
	if !is_zero_gemini_function_response(value.function_response) {
		oj.write_key(w, "functionResponse")
		marshal_gemini_function_response(w, value.function_response)
	}
	oj.write_object_end(w)
}

// Unmarshals JSON into Gemini_Content
// Source: gemini (src/providers/gemini/types.odin)
unmarshal_gemini_content :: proc(r: ^oj.Reader, path: string = "") -> (result: Gemini_Content, err: oj.Error) {
	elem, elem_err := oj.element_at(r, path)
	if elem_err != .OK do return result, elem_err
	return unmarshal_gemini_content_elem(r, elem)
}

// Unmarshals JSON element into Gemini_Content
unmarshal_gemini_content_elem :: proc(r: ^oj.Reader, elem: oj.Element) -> (result: Gemini_Content, err: oj.Error) {
	result.role, err = oj.read_string_elem(r, elem, "role")
	if err != .OK && err != .Key_Not_Found && err != .Type_Mismatch do return

	{
		arr_elem, arr_err := oj.obj_element_from(r, elem, "parts")
		if arr_err == .OK {
			items, _ := oj.array_elements_from(r, arr_elem)
			result.parts = make([]Gemini_Part, len(items))
			for item_elem, i in items {
				result.parts[i], err = unmarshal_gemini_part_elem(r, item_elem)
				if err != .OK do return
			}
		}
	}

	return
}

is_zero_gemini_content :: proc(v: Gemini_Content) -> bool {
	return v.role == "" && len(v.parts) == 0
}

// Marshals Gemini_Content to JSON
marshal_gemini_content :: proc(w: ^oj.Writer, value: Gemini_Content) {
	oj.write_object_start(w)
	if value.role != "" {
		oj.write_key(w, "role")
		oj.write_string(w, value.role)
	}
	oj.write_key(w, "parts")
	oj.write_array_start(w)
	for item in value.parts {
		marshal_gemini_part(w, item)
	}
	oj.write_array_end(w)
	oj.write_object_end(w)
}

// Unmarshals JSON into Gemini_System_Instruction
// Source: gemini (src/providers/gemini/types.odin)
unmarshal_gemini_system_instruction :: proc(r: ^oj.Reader, path: string = "") -> (result: Gemini_System_Instruction, err: oj.Error) {
	elem, elem_err := oj.element_at(r, path)
	if elem_err != .OK do return result, elem_err
	return unmarshal_gemini_system_instruction_elem(r, elem)
}

// Unmarshals JSON element into Gemini_System_Instruction
unmarshal_gemini_system_instruction_elem :: proc(r: ^oj.Reader, elem: oj.Element) -> (result: Gemini_System_Instruction, err: oj.Error) {
	{
		arr_elem, arr_err := oj.obj_element_from(r, elem, "parts")
		if arr_err == .OK {
			items, _ := oj.array_elements_from(r, arr_elem)
			result.parts = make([]Gemini_Part, len(items))
			for item_elem, i in items {
				result.parts[i], err = unmarshal_gemini_part_elem(r, item_elem)
				if err != .OK do return
			}
		}
	}

	return
}

is_zero_gemini_system_instruction :: proc(v: Gemini_System_Instruction) -> bool {
	return len(v.parts) == 0
}

// Marshals Gemini_System_Instruction to JSON
marshal_gemini_system_instruction :: proc(w: ^oj.Writer, value: Gemini_System_Instruction) {
	oj.write_object_start(w)
	oj.write_key(w, "parts")
	oj.write_array_start(w)
	for item in value.parts {
		marshal_gemini_part(w, item)
	}
	oj.write_array_end(w)
	oj.write_object_end(w)
}

// Unmarshals JSON into Gemini_Tool_Declaration
// Source: gemini (src/providers/gemini/types.odin)
unmarshal_gemini_tool_declaration :: proc(r: ^oj.Reader, path: string = "") -> (result: Gemini_Tool_Declaration, err: oj.Error) {
	elem, elem_err := oj.element_at(r, path)
	if elem_err != .OK do return result, elem_err
	return unmarshal_gemini_tool_declaration_elem(r, elem)
}

// Unmarshals JSON element into Gemini_Tool_Declaration
unmarshal_gemini_tool_declaration_elem :: proc(r: ^oj.Reader, elem: oj.Element) -> (result: Gemini_Tool_Declaration, err: oj.Error) {
	result.name, err = oj.read_string_elem(r, elem, "name")
	if err != .OK && err != .Key_Not_Found && err != .Type_Mismatch do return

	result.description, err = oj.read_string_elem(r, elem, "description")
	if err != .OK && err != .Key_Not_Found && err != .Type_Mismatch do return

	{
		raw_val, raw_err := oj.read_raw_elem(r, elem, "parameters")
		if raw_err != .OK && raw_err != .Key_Not_Found && raw_err != .Type_Mismatch do return result, raw_err
		if raw_err == .OK do result.parameters = raw_val
	}

	return
}

is_zero_gemini_tool_declaration :: proc(v: Gemini_Tool_Declaration) -> bool {
	return v.name == "" && v.description == "" && v.parameters == ""
}

// Marshals Gemini_Tool_Declaration to JSON
marshal_gemini_tool_declaration :: proc(w: ^oj.Writer, value: Gemini_Tool_Declaration) {
	oj.write_object_start(w)
	oj.write_key(w, "name")
	oj.write_string(w, value.name)
	oj.write_key(w, "description")
	oj.write_string(w, value.description)
	oj.write_key(w, "parameters")
	oj.write_raw(w, value.parameters)
	oj.write_object_end(w)
}

// Unmarshals JSON into Gemini_Tool
// Source: gemini (src/providers/gemini/types.odin)
unmarshal_gemini_tool :: proc(r: ^oj.Reader, path: string = "") -> (result: Gemini_Tool, err: oj.Error) {
	elem, elem_err := oj.element_at(r, path)
	if elem_err != .OK do return result, elem_err
	return unmarshal_gemini_tool_elem(r, elem)
}

// Unmarshals JSON element into Gemini_Tool
unmarshal_gemini_tool_elem :: proc(r: ^oj.Reader, elem: oj.Element) -> (result: Gemini_Tool, err: oj.Error) {
	{
		arr_elem, arr_err := oj.obj_element_from(r, elem, "functionDeclarations")
		if arr_err == .OK {
			items, _ := oj.array_elements_from(r, arr_elem)
			result.function_declarations = make([]Gemini_Tool_Declaration, len(items))
			for item_elem, i in items {
				result.function_declarations[i], err = unmarshal_gemini_tool_declaration_elem(r, item_elem)
				if err != .OK do return
			}
		}
	}

	return
}

is_zero_gemini_tool :: proc(v: Gemini_Tool) -> bool {
	return len(v.function_declarations) == 0
}

// Marshals Gemini_Tool to JSON
marshal_gemini_tool :: proc(w: ^oj.Writer, value: Gemini_Tool) {
	oj.write_object_start(w)
	oj.write_key(w, "functionDeclarations")
	oj.write_array_start(w)
	for item in value.function_declarations {
		marshal_gemini_tool_declaration(w, item)
	}
	oj.write_array_end(w)
	oj.write_object_end(w)
}

// Unmarshals JSON into Gemini_Generation_Config
// Source: gemini (src/providers/gemini/types.odin)
unmarshal_gemini_generation_config :: proc(r: ^oj.Reader, path: string = "") -> (result: Gemini_Generation_Config, err: oj.Error) {
	elem, elem_err := oj.element_at(r, path)
	if elem_err != .OK do return result, elem_err
	return unmarshal_gemini_generation_config_elem(r, elem)
}

// Unmarshals JSON element into Gemini_Generation_Config
unmarshal_gemini_generation_config_elem :: proc(r: ^oj.Reader, elem: oj.Element) -> (result: Gemini_Generation_Config, err: oj.Error) {
	{
		val: f64
		val, err = oj.read_f64_elem(r, elem, "temperature")
		if err != .OK && err != .Key_Not_Found && err != .Type_Mismatch do return
		if err == .OK do result.temperature = f32(val)
	}

	result.max_output_tokens, err = oj.read_int_elem(r, elem, "maxOutputTokens")
	if err != .OK && err != .Key_Not_Found && err != .Type_Mismatch do return

	{
		raw_val, raw_err := oj.read_raw_elem(r, elem, "thinkingConfig")
		if raw_err != .OK && raw_err != .Key_Not_Found && raw_err != .Type_Mismatch do return result, raw_err
		if raw_err == .OK do result.thinking_config = raw_val
	}

	return
}

is_zero_gemini_generation_config :: proc(v: Gemini_Generation_Config) -> bool {
	return v.temperature == 0 && v.max_output_tokens == 0 && v.thinking_config == ""
}

// Marshals Gemini_Generation_Config to JSON
marshal_gemini_generation_config :: proc(w: ^oj.Writer, value: Gemini_Generation_Config) {
	oj.write_object_start(w)
	oj.write_key(w, "temperature")
	oj.write_f32(w, value.temperature)
	oj.write_key(w, "maxOutputTokens")
	oj.write_int(w, value.max_output_tokens)
	if value.thinking_config != "" {
		oj.write_key(w, "thinkingConfig")
		oj.write_raw(w, value.thinking_config)
	}
	oj.write_object_end(w)
}

// Unmarshals JSON into Gemini_Request
// Source: gemini (src/providers/gemini/types.odin)
unmarshal_gemini_request :: proc(r: ^oj.Reader, path: string = "") -> (result: Gemini_Request, err: oj.Error) {
	elem, elem_err := oj.element_at(r, path)
	if elem_err != .OK do return result, elem_err
	return unmarshal_gemini_request_elem(r, elem)
}

// Unmarshals JSON element into Gemini_Request
unmarshal_gemini_request_elem :: proc(r: ^oj.Reader, elem: oj.Element) -> (result: Gemini_Request, err: oj.Error) {
	{
		nested_elem, nested_err := oj.obj_element_from(r, elem, "systemInstruction")
		if nested_err == .OK {
			result.system_instruction, err = unmarshal_gemini_system_instruction_elem(r, nested_elem)
			if err != .OK do return
		}
	}

	{
		arr_elem, arr_err := oj.obj_element_from(r, elem, "contents")
		if arr_err == .OK {
			items, _ := oj.array_elements_from(r, arr_elem)
			result.contents = make([]Gemini_Content, len(items))
			for item_elem, i in items {
				result.contents[i], err = unmarshal_gemini_content_elem(r, item_elem)
				if err != .OK do return
			}
		}
	}

	{
		arr_elem, arr_err := oj.obj_element_from(r, elem, "tools")
		if arr_err == .OK {
			items, _ := oj.array_elements_from(r, arr_elem)
			result.tools = make([]Gemini_Tool, len(items))
			for item_elem, i in items {
				result.tools[i], err = unmarshal_gemini_tool_elem(r, item_elem)
				if err != .OK do return
			}
		}
	}

	{
		nested_elem, nested_err := oj.obj_element_from(r, elem, "generationConfig")
		if nested_err == .OK {
			result.generation_config, err = unmarshal_gemini_generation_config_elem(r, nested_elem)
			if err != .OK do return
		}
	}

	return
}

is_zero_gemini_request :: proc(v: Gemini_Request) -> bool {
	return is_zero_gemini_system_instruction(v.system_instruction) && len(v.contents) == 0 && len(v.tools) == 0 && is_zero_gemini_generation_config(v.generation_config)
}

// Marshals Gemini_Request to JSON
marshal_gemini_request :: proc(w: ^oj.Writer, value: Gemini_Request) {
	oj.write_object_start(w)
	if !is_zero_gemini_system_instruction(value.system_instruction) {
		oj.write_key(w, "systemInstruction")
		marshal_gemini_system_instruction(w, value.system_instruction)
	}
	oj.write_key(w, "contents")
	oj.write_array_start(w)
	for item in value.contents {
		marshal_gemini_content(w, item)
	}
	oj.write_array_end(w)
	if len(value.tools) > 0 {
		oj.write_key(w, "tools")
	oj.write_array_start(w)
	for item in value.tools {
		marshal_gemini_tool(w, item)
	}
	oj.write_array_end(w)
	}
	oj.write_key(w, "generationConfig")
	marshal_gemini_generation_config(w, value.generation_config)
	oj.write_object_end(w)
}

// Unmarshals JSON into Gemini_Candidate
// Source: gemini (src/providers/gemini/types.odin)
unmarshal_gemini_candidate :: proc(r: ^oj.Reader, path: string = "") -> (result: Gemini_Candidate, err: oj.Error) {
	elem, elem_err := oj.element_at(r, path)
	if elem_err != .OK do return result, elem_err
	return unmarshal_gemini_candidate_elem(r, elem)
}

// Unmarshals JSON element into Gemini_Candidate
unmarshal_gemini_candidate_elem :: proc(r: ^oj.Reader, elem: oj.Element) -> (result: Gemini_Candidate, err: oj.Error) {
	{
		nested_elem, nested_err := oj.obj_element_from(r, elem, "content")
		if nested_err == .OK {
			result.content, err = unmarshal_gemini_content_elem(r, nested_elem)
			if err != .OK do return
		}
	}

	result.finish_reason, err = oj.read_string_elem(r, elem, "finishReason")
	if err != .OK && err != .Key_Not_Found && err != .Type_Mismatch do return

	return
}

is_zero_gemini_candidate :: proc(v: Gemini_Candidate) -> bool {
	return is_zero_gemini_content(v.content) && v.finish_reason == ""
}

// Marshals Gemini_Candidate to JSON
marshal_gemini_candidate :: proc(w: ^oj.Writer, value: Gemini_Candidate) {
	oj.write_object_start(w)
	oj.write_key(w, "content")
	marshal_gemini_content(w, value.content)
	oj.write_key(w, "finishReason")
	oj.write_string(w, value.finish_reason)
	oj.write_object_end(w)
}

// Unmarshals JSON into Gemini_Usage_Metadata
// Source: gemini (src/providers/gemini/types.odin)
unmarshal_gemini_usage_metadata :: proc(r: ^oj.Reader, path: string = "") -> (result: Gemini_Usage_Metadata, err: oj.Error) {
	elem, elem_err := oj.element_at(r, path)
	if elem_err != .OK do return result, elem_err
	return unmarshal_gemini_usage_metadata_elem(r, elem)
}

// Unmarshals JSON element into Gemini_Usage_Metadata
unmarshal_gemini_usage_metadata_elem :: proc(r: ^oj.Reader, elem: oj.Element) -> (result: Gemini_Usage_Metadata, err: oj.Error) {
	result.prompt_token_count, err = oj.read_int_elem(r, elem, "promptTokenCount")
	if err != .OK && err != .Key_Not_Found && err != .Type_Mismatch do return

	result.candidates_token_count, err = oj.read_int_elem(r, elem, "candidatesTokenCount")
	if err != .OK && err != .Key_Not_Found && err != .Type_Mismatch do return

	result.cached_content_token_count, err = oj.read_int_elem(r, elem, "cachedContentTokenCount")
	if err != .OK && err != .Key_Not_Found && err != .Type_Mismatch do return

	result.thoughts_token_count, err = oj.read_int_elem(r, elem, "thoughtsTokenCount")
	if err != .OK && err != .Key_Not_Found && err != .Type_Mismatch do return

	return
}

is_zero_gemini_usage_metadata :: proc(v: Gemini_Usage_Metadata) -> bool {
	return v.prompt_token_count == 0 && v.candidates_token_count == 0 && v.cached_content_token_count == 0 && v.thoughts_token_count == 0
}

// Marshals Gemini_Usage_Metadata to JSON
marshal_gemini_usage_metadata :: proc(w: ^oj.Writer, value: Gemini_Usage_Metadata) {
	oj.write_object_start(w)
	oj.write_key(w, "promptTokenCount")
	oj.write_int(w, value.prompt_token_count)
	oj.write_key(w, "candidatesTokenCount")
	oj.write_int(w, value.candidates_token_count)
	oj.write_key(w, "cachedContentTokenCount")
	oj.write_int(w, value.cached_content_token_count)
	oj.write_key(w, "thoughtsTokenCount")
	oj.write_int(w, value.thoughts_token_count)
	oj.write_object_end(w)
}

// Unmarshals JSON into Gemini_Response
// Source: gemini (src/providers/gemini/types.odin)
unmarshal_gemini_response :: proc(r: ^oj.Reader, path: string = "") -> (result: Gemini_Response, err: oj.Error) {
	elem, elem_err := oj.element_at(r, path)
	if elem_err != .OK do return result, elem_err
	return unmarshal_gemini_response_elem(r, elem)
}

// Unmarshals JSON element into Gemini_Response
unmarshal_gemini_response_elem :: proc(r: ^oj.Reader, elem: oj.Element) -> (result: Gemini_Response, err: oj.Error) {
	{
		arr_elem, arr_err := oj.obj_element_from(r, elem, "candidates")
		if arr_err == .OK {
			items, _ := oj.array_elements_from(r, arr_elem)
			result.candidates = make([]Gemini_Candidate, len(items))
			for item_elem, i in items {
				result.candidates[i], err = unmarshal_gemini_candidate_elem(r, item_elem)
				if err != .OK do return
			}
		}
	}

	{
		nested_elem, nested_err := oj.obj_element_from(r, elem, "usageMetadata")
		if nested_err == .OK {
			result.usage_metadata, err = unmarshal_gemini_usage_metadata_elem(r, nested_elem)
			if err != .OK do return
		}
	}

	return
}

is_zero_gemini_response :: proc(v: Gemini_Response) -> bool {
	return len(v.candidates) == 0 && is_zero_gemini_usage_metadata(v.usage_metadata)
}

// Marshals Gemini_Response to JSON
marshal_gemini_response :: proc(w: ^oj.Writer, value: Gemini_Response) {
	oj.write_object_start(w)
	oj.write_key(w, "candidates")
	oj.write_array_start(w)
	for item in value.candidates {
		marshal_gemini_candidate(w, item)
	}
	oj.write_array_end(w)
	oj.write_key(w, "usageMetadata")
	marshal_gemini_usage_metadata(w, value.usage_metadata)
	oj.write_object_end(w)
}
