// Code generated by ojson generator. DO NOT EDIT.
package anthropic

import oj "../../../pkgs/ojson/jsonimpl"

// Unmarshals JSON into Anthropic_Content_Block (tagged union)
// Source: anthropic (src/providers/anthropic/types.odin)
unmarshal_anthropic_content_block :: proc(
	r: ^oj.Reader,
	path: string = "",
) -> (
	result: Anthropic_Content_Block,
	err: oj.Error,
) {
	elem, elem_err := oj.element_at(r, path)
	if elem_err != .OK do return result, elem_err
	return unmarshal_anthropic_content_block_elem(r, elem)
}

// Unmarshals JSON element into Anthropic_Content_Block (tagged union)
unmarshal_anthropic_content_block_elem :: proc(
	r: ^oj.Reader,
	elem: oj.Element,
) -> (
	result: Anthropic_Content_Block,
	err: oj.Error,
) {
	discr, _ := oj.read_string_elem(r, elem, "type")
	switch discr {
	case "text":
		variant, v_err := unmarshal_anthropic_text_block_elem(r, elem)
		result = variant
		err = v_err
	case "thinking":
		variant, v_err := unmarshal_anthropic_thinking_block_elem(r, elem)
		result = variant
		err = v_err
	case "tool_use":
		variant, v_err := unmarshal_anthropic_tool_use_block_elem(r, elem)
		result = variant
		err = v_err
	case "tool_result":
		variant, v_err := unmarshal_anthropic_tool_result_block_elem(r, elem)
		result = variant
		err = v_err
	}
	return
}

// Marshals Anthropic_Content_Block (tagged union) to JSON
marshal_anthropic_content_block :: proc(w: ^oj.Writer, value: Anthropic_Content_Block) {
	switch variant in value {
	case Anthropic_Text_Block:
		marshal_anthropic_text_block(w, variant)
	case Anthropic_Thinking_Block:
		marshal_anthropic_thinking_block(w, variant)
	case Anthropic_Tool_Use_Block:
		marshal_anthropic_tool_use_block(w, variant)
	case Anthropic_Tool_Result_Block:
		marshal_anthropic_tool_result_block(w, variant)
	}
}

// Unmarshals JSON into Anthropic_Cache_Control
// Source: anthropic (src/providers/anthropic/types.odin)
unmarshal_anthropic_cache_control :: proc(
	r: ^oj.Reader,
	path: string = "",
) -> (
	result: Anthropic_Cache_Control,
	err: oj.Error,
) {
	elem, elem_err := oj.element_at(r, path)
	if elem_err != .OK do return result, elem_err
	return unmarshal_anthropic_cache_control_elem(r, elem)
}

// Unmarshals JSON element into Anthropic_Cache_Control
unmarshal_anthropic_cache_control_elem :: proc(
	r: ^oj.Reader,
	elem: oj.Element,
) -> (
	result: Anthropic_Cache_Control,
	err: oj.Error,
) {
	result.type, err = oj.read_string_elem(r, elem, "type")
	if err != .OK && err != .Key_Not_Found && err != .Type_Mismatch do return

	return
}

is_zero_anthropic_cache_control :: proc(v: Anthropic_Cache_Control) -> bool {
	return v.type == ""
}

// Marshals Anthropic_Cache_Control to JSON
marshal_anthropic_cache_control :: proc(w: ^oj.Writer, value: Anthropic_Cache_Control) {
	oj.write_object_start(w)
	oj.write_key(w, "type")
	oj.write_string(w, value.type)
	oj.write_object_end(w)
}

// Unmarshals JSON into Anthropic_Thinking
// Source: anthropic (src/providers/anthropic/types.odin)
unmarshal_anthropic_thinking :: proc(
	r: ^oj.Reader,
	path: string = "",
) -> (
	result: Anthropic_Thinking,
	err: oj.Error,
) {
	elem, elem_err := oj.element_at(r, path)
	if elem_err != .OK do return result, elem_err
	return unmarshal_anthropic_thinking_elem(r, elem)
}

// Unmarshals JSON element into Anthropic_Thinking
unmarshal_anthropic_thinking_elem :: proc(
	r: ^oj.Reader,
	elem: oj.Element,
) -> (
	result: Anthropic_Thinking,
	err: oj.Error,
) {
	result.type, err = oj.read_string_elem(r, elem, "type")
	if err != .OK && err != .Key_Not_Found && err != .Type_Mismatch do return

	result.budget_tokens, err = oj.read_int_elem(r, elem, "budget_tokens")
	if err != .OK && err != .Key_Not_Found && err != .Type_Mismatch do return

	return
}

is_zero_anthropic_thinking :: proc(v: Anthropic_Thinking) -> bool {
	return v.type == "" && v.budget_tokens == 0
}

// Marshals Anthropic_Thinking to JSON
marshal_anthropic_thinking :: proc(w: ^oj.Writer, value: Anthropic_Thinking) {
	oj.write_object_start(w)
	oj.write_key(w, "type")
	oj.write_string(w, value.type)
	oj.write_key(w, "budget_tokens")
	oj.write_int(w, value.budget_tokens)
	oj.write_object_end(w)
}

// Unmarshals JSON into Anthropic_Text_Block
// Source: anthropic (src/providers/anthropic/types.odin)
unmarshal_anthropic_text_block :: proc(
	r: ^oj.Reader,
	path: string = "",
) -> (
	result: Anthropic_Text_Block,
	err: oj.Error,
) {
	elem, elem_err := oj.element_at(r, path)
	if elem_err != .OK do return result, elem_err
	return unmarshal_anthropic_text_block_elem(r, elem)
}

// Unmarshals JSON element into Anthropic_Text_Block
unmarshal_anthropic_text_block_elem :: proc(
	r: ^oj.Reader,
	elem: oj.Element,
) -> (
	result: Anthropic_Text_Block,
	err: oj.Error,
) {
	result.type, err = oj.read_string_elem(r, elem, "type")
	if err != .OK && err != .Key_Not_Found && err != .Type_Mismatch do return

	result.text, err = oj.read_string_elem(r, elem, "text")
	if err != .OK && err != .Key_Not_Found && err != .Type_Mismatch do return

	{
		nested_elem, nested_err := oj.obj_element_from(r, elem, "cache_control")
		if nested_err == .OK {
			result.cache_control, err = unmarshal_anthropic_cache_control_elem(r, nested_elem)
			if err != .OK do return
		}
	}

	return
}

is_zero_anthropic_text_block :: proc(v: Anthropic_Text_Block) -> bool {
	return v.type == "" && v.text == "" && is_zero_anthropic_cache_control(v.cache_control)
}

// Marshals Anthropic_Text_Block to JSON
marshal_anthropic_text_block :: proc(w: ^oj.Writer, value: Anthropic_Text_Block) {
	oj.write_object_start(w)
	oj.write_key(w, "type")
	oj.write_string(w, "text")
	oj.write_key(w, "text")
	oj.write_string(w, value.text)
	if !is_zero_anthropic_cache_control(value.cache_control) {
		oj.write_key(w, "cache_control")
		marshal_anthropic_cache_control(w, value.cache_control)
	}
	oj.write_object_end(w)
}

// Unmarshals JSON into Anthropic_Thinking_Block
// Source: anthropic (src/providers/anthropic/types.odin)
unmarshal_anthropic_thinking_block :: proc(
	r: ^oj.Reader,
	path: string = "",
) -> (
	result: Anthropic_Thinking_Block,
	err: oj.Error,
) {
	elem, elem_err := oj.element_at(r, path)
	if elem_err != .OK do return result, elem_err
	return unmarshal_anthropic_thinking_block_elem(r, elem)
}

// Unmarshals JSON element into Anthropic_Thinking_Block
unmarshal_anthropic_thinking_block_elem :: proc(
	r: ^oj.Reader,
	elem: oj.Element,
) -> (
	result: Anthropic_Thinking_Block,
	err: oj.Error,
) {
	result.type, err = oj.read_string_elem(r, elem, "type")
	if err != .OK && err != .Key_Not_Found && err != .Type_Mismatch do return

	result.thinking, err = oj.read_string_elem(r, elem, "thinking")
	if err != .OK && err != .Key_Not_Found && err != .Type_Mismatch do return

	result.signature, err = oj.read_string_elem(r, elem, "signature")
	if err != .OK && err != .Key_Not_Found && err != .Type_Mismatch do return

	return
}

is_zero_anthropic_thinking_block :: proc(v: Anthropic_Thinking_Block) -> bool {
	return v.type == "" && v.thinking == "" && v.signature == ""
}

// Marshals Anthropic_Thinking_Block to JSON
marshal_anthropic_thinking_block :: proc(w: ^oj.Writer, value: Anthropic_Thinking_Block) {
	oj.write_object_start(w)
	oj.write_key(w, "type")
	oj.write_string(w, "thinking")
	oj.write_key(w, "thinking")
	oj.write_string(w, value.thinking)
	oj.write_key(w, "signature")
	oj.write_string(w, value.signature)
	oj.write_object_end(w)
}

// Unmarshals JSON into Anthropic_Tool_Use_Block
// Source: anthropic (src/providers/anthropic/types.odin)
unmarshal_anthropic_tool_use_block :: proc(
	r: ^oj.Reader,
	path: string = "",
) -> (
	result: Anthropic_Tool_Use_Block,
	err: oj.Error,
) {
	elem, elem_err := oj.element_at(r, path)
	if elem_err != .OK do return result, elem_err
	return unmarshal_anthropic_tool_use_block_elem(r, elem)
}

// Unmarshals JSON element into Anthropic_Tool_Use_Block
unmarshal_anthropic_tool_use_block_elem :: proc(
	r: ^oj.Reader,
	elem: oj.Element,
) -> (
	result: Anthropic_Tool_Use_Block,
	err: oj.Error,
) {
	result.type, err = oj.read_string_elem(r, elem, "type")
	if err != .OK && err != .Key_Not_Found && err != .Type_Mismatch do return

	result.id, err = oj.read_string_elem(r, elem, "id")
	if err != .OK && err != .Key_Not_Found && err != .Type_Mismatch do return

	result.name, err = oj.read_string_elem(r, elem, "name")
	if err != .OK && err != .Key_Not_Found && err != .Type_Mismatch do return

	{
		raw_val, raw_err := oj.read_raw_elem(r, elem, "input")
		if raw_err != .OK && raw_err != .Key_Not_Found && raw_err != .Type_Mismatch do return result, raw_err
		if raw_err == .OK do result.input = raw_val
	}

	return
}

is_zero_anthropic_tool_use_block :: proc(v: Anthropic_Tool_Use_Block) -> bool {
	return v.type == "" && v.id == "" && v.name == "" && v.input == ""
}

// Marshals Anthropic_Tool_Use_Block to JSON
marshal_anthropic_tool_use_block :: proc(w: ^oj.Writer, value: Anthropic_Tool_Use_Block) {
	oj.write_object_start(w)
	oj.write_key(w, "type")
	oj.write_string(w, "tool_use")
	oj.write_key(w, "id")
	oj.write_string(w, value.id)
	oj.write_key(w, "name")
	oj.write_string(w, value.name)
	oj.write_key(w, "input")
	oj.write_raw(w, value.input)
	oj.write_object_end(w)
}

// Unmarshals JSON into Anthropic_Tool_Result_Block
// Source: anthropic (src/providers/anthropic/types.odin)
unmarshal_anthropic_tool_result_block :: proc(
	r: ^oj.Reader,
	path: string = "",
) -> (
	result: Anthropic_Tool_Result_Block,
	err: oj.Error,
) {
	elem, elem_err := oj.element_at(r, path)
	if elem_err != .OK do return result, elem_err
	return unmarshal_anthropic_tool_result_block_elem(r, elem)
}

// Unmarshals JSON element into Anthropic_Tool_Result_Block
unmarshal_anthropic_tool_result_block_elem :: proc(
	r: ^oj.Reader,
	elem: oj.Element,
) -> (
	result: Anthropic_Tool_Result_Block,
	err: oj.Error,
) {
	result.type, err = oj.read_string_elem(r, elem, "type")
	if err != .OK && err != .Key_Not_Found && err != .Type_Mismatch do return

	result.tool_use_id, err = oj.read_string_elem(r, elem, "tool_use_id")
	if err != .OK && err != .Key_Not_Found && err != .Type_Mismatch do return

	result.content, err = oj.read_string_elem(r, elem, "content")
	if err != .OK && err != .Key_Not_Found && err != .Type_Mismatch do return

	return
}

is_zero_anthropic_tool_result_block :: proc(v: Anthropic_Tool_Result_Block) -> bool {
	return v.type == "" && v.tool_use_id == "" && v.content == ""
}

// Marshals Anthropic_Tool_Result_Block to JSON
marshal_anthropic_tool_result_block :: proc(w: ^oj.Writer, value: Anthropic_Tool_Result_Block) {
	oj.write_object_start(w)
	oj.write_key(w, "type")
	oj.write_string(w, "tool_result")
	oj.write_key(w, "tool_use_id")
	oj.write_string(w, value.tool_use_id)
	oj.write_key(w, "content")
	oj.write_string(w, value.content)
	oj.write_object_end(w)
}

// Unmarshals JSON into Anthropic_Message
// Source: anthropic (src/providers/anthropic/types.odin)
unmarshal_anthropic_message :: proc(
	r: ^oj.Reader,
	path: string = "",
) -> (
	result: Anthropic_Message,
	err: oj.Error,
) {
	elem, elem_err := oj.element_at(r, path)
	if elem_err != .OK do return result, elem_err
	return unmarshal_anthropic_message_elem(r, elem)
}

// Unmarshals JSON element into Anthropic_Message
unmarshal_anthropic_message_elem :: proc(
	r: ^oj.Reader,
	elem: oj.Element,
) -> (
	result: Anthropic_Message,
	err: oj.Error,
) {
	result.role, err = oj.read_string_elem(r, elem, "role")
	if err != .OK && err != .Key_Not_Found && err != .Type_Mismatch do return

	{
		arr_elem, arr_err := oj.obj_element_from(r, elem, "content")
		if arr_err == .OK {
			items, _ := oj.array_elements_from(r, arr_elem)
			result.content = make([]Anthropic_Content_Block, len(items))
			for item_elem, i in items {
				result.content[i], err = unmarshal_anthropic_content_block_elem(r, item_elem)
				if err != .OK do return
			}
		}
	}

	return
}

is_zero_anthropic_message :: proc(v: Anthropic_Message) -> bool {
	return v.role == "" && len(v.content) == 0
}

// Marshals Anthropic_Message to JSON
marshal_anthropic_message :: proc(w: ^oj.Writer, value: Anthropic_Message) {
	oj.write_object_start(w)
	oj.write_key(w, "role")
	oj.write_string(w, value.role)
	oj.write_key(w, "content")
	oj.write_array_start(w)
	for item in value.content {
		marshal_anthropic_content_block(w, item)
	}
	oj.write_array_end(w)
	oj.write_object_end(w)
}

// Unmarshals JSON into Anthropic_Tool
// Source: anthropic (src/providers/anthropic/types.odin)
unmarshal_anthropic_tool :: proc(
	r: ^oj.Reader,
	path: string = "",
) -> (
	result: Anthropic_Tool,
	err: oj.Error,
) {
	elem, elem_err := oj.element_at(r, path)
	if elem_err != .OK do return result, elem_err
	return unmarshal_anthropic_tool_elem(r, elem)
}

// Unmarshals JSON element into Anthropic_Tool
unmarshal_anthropic_tool_elem :: proc(
	r: ^oj.Reader,
	elem: oj.Element,
) -> (
	result: Anthropic_Tool,
	err: oj.Error,
) {
	result.name, err = oj.read_string_elem(r, elem, "name")
	if err != .OK && err != .Key_Not_Found && err != .Type_Mismatch do return

	result.description, err = oj.read_string_elem(r, elem, "description")
	if err != .OK && err != .Key_Not_Found && err != .Type_Mismatch do return

	{
		raw_val, raw_err := oj.read_raw_elem(r, elem, "input_schema")
		if raw_err != .OK && raw_err != .Key_Not_Found && raw_err != .Type_Mismatch do return result, raw_err
		if raw_err == .OK do result.input_schema = raw_val
	}

	{
		nested_elem, nested_err := oj.obj_element_from(r, elem, "cache_control")
		if nested_err == .OK {
			result.cache_control, err = unmarshal_anthropic_cache_control_elem(r, nested_elem)
			if err != .OK do return
		}
	}

	return
}

is_zero_anthropic_tool :: proc(v: Anthropic_Tool) -> bool {
	return(
		v.name == "" &&
		v.description == "" &&
		v.input_schema == "" &&
		is_zero_anthropic_cache_control(v.cache_control) \
	)
}

// Marshals Anthropic_Tool to JSON
marshal_anthropic_tool :: proc(w: ^oj.Writer, value: Anthropic_Tool) {
	oj.write_object_start(w)
	oj.write_key(w, "name")
	oj.write_string(w, value.name)
	oj.write_key(w, "description")
	oj.write_string(w, value.description)
	oj.write_key(w, "input_schema")
	oj.write_raw(w, value.input_schema)
	if !is_zero_anthropic_cache_control(value.cache_control) {
		oj.write_key(w, "cache_control")
		marshal_anthropic_cache_control(w, value.cache_control)
	}
	oj.write_object_end(w)
}

// Unmarshals JSON into Anthropic_Request
// Source: anthropic (src/providers/anthropic/types.odin)
unmarshal_anthropic_request :: proc(
	r: ^oj.Reader,
	path: string = "",
) -> (
	result: Anthropic_Request,
	err: oj.Error,
) {
	elem, elem_err := oj.element_at(r, path)
	if elem_err != .OK do return result, elem_err
	return unmarshal_anthropic_request_elem(r, elem)
}

// Unmarshals JSON element into Anthropic_Request
unmarshal_anthropic_request_elem :: proc(
	r: ^oj.Reader,
	elem: oj.Element,
) -> (
	result: Anthropic_Request,
	err: oj.Error,
) {
	result.model, err = oj.read_string_elem(r, elem, "model")
	if err != .OK && err != .Key_Not_Found && err != .Type_Mismatch do return

	result.max_tokens, err = oj.read_int_elem(r, elem, "max_tokens")
	if err != .OK && err != .Key_Not_Found && err != .Type_Mismatch do return

	{
		raw_val, raw_err := oj.read_raw_elem(r, elem, "temperature")
		if raw_err != .OK && raw_err != .Key_Not_Found && raw_err != .Type_Mismatch do return result, raw_err
		if raw_err == .OK do result.temperature = raw_val
	}

	{
		nested_elem, nested_err := oj.obj_element_from(r, elem, "thinking")
		if nested_err == .OK {
			result.thinking, err = unmarshal_anthropic_thinking_elem(r, nested_elem)
			if err != .OK do return
		}
	}

	result.stream, err = oj.read_bool_elem(r, elem, "stream")
	if err != .OK && err != .Key_Not_Found && err != .Type_Mismatch do return

	{
		arr_elem, arr_err := oj.obj_element_from(r, elem, "system")
		if arr_err == .OK {
			items, _ := oj.array_elements_from(r, arr_elem)
			result.system = make([]Anthropic_Text_Block, len(items))
			for item_elem, i in items {
				result.system[i], err = unmarshal_anthropic_text_block_elem(r, item_elem)
				if err != .OK do return
			}
		}
	}

	{
		arr_elem, arr_err := oj.obj_element_from(r, elem, "messages")
		if arr_err == .OK {
			items, _ := oj.array_elements_from(r, arr_elem)
			result.messages = make([]Anthropic_Message, len(items))
			for item_elem, i in items {
				result.messages[i], err = unmarshal_anthropic_message_elem(r, item_elem)
				if err != .OK do return
			}
		}
	}

	{
		arr_elem, arr_err := oj.obj_element_from(r, elem, "tools")
		if arr_err == .OK {
			items, _ := oj.array_elements_from(r, arr_elem)
			result.tools = make([]Anthropic_Tool, len(items))
			for item_elem, i in items {
				result.tools[i], err = unmarshal_anthropic_tool_elem(r, item_elem)
				if err != .OK do return
			}
		}
	}

	return
}

is_zero_anthropic_request :: proc(v: Anthropic_Request) -> bool {
	return(
		v.model == "" &&
		v.max_tokens == 0 &&
		v.temperature == "" &&
		is_zero_anthropic_thinking(v.thinking) &&
		!v.stream &&
		len(v.system) == 0 &&
		len(v.messages) == 0 &&
		len(v.tools) == 0 \
	)
}

// Marshals Anthropic_Request to JSON
marshal_anthropic_request :: proc(w: ^oj.Writer, value: Anthropic_Request) {
	oj.write_object_start(w)
	oj.write_key(w, "model")
	oj.write_string(w, value.model)
	oj.write_key(w, "max_tokens")
	oj.write_int(w, value.max_tokens)
	if value.temperature != "" {
		oj.write_key(w, "temperature")
		oj.write_raw(w, value.temperature)
	}
	if !is_zero_anthropic_thinking(value.thinking) {
		oj.write_key(w, "thinking")
		marshal_anthropic_thinking(w, value.thinking)
	}
	if value.stream {
		oj.write_key(w, "stream")
		oj.write_bool(w, value.stream)
	}
	if len(value.system) > 0 {
		oj.write_key(w, "system")
		oj.write_array_start(w)
		for item in value.system {
			marshal_anthropic_text_block(w, item)
		}
		oj.write_array_end(w)
	}
	oj.write_key(w, "messages")
	oj.write_array_start(w)
	for item in value.messages {
		marshal_anthropic_message(w, item)
	}
	oj.write_array_end(w)
	if len(value.tools) > 0 {
		oj.write_key(w, "tools")
		oj.write_array_start(w)
		for item in value.tools {
			marshal_anthropic_tool(w, item)
		}
		oj.write_array_end(w)
	}
	oj.write_object_end(w)
}

// Unmarshals JSON into Anthropic_Usage
// Source: anthropic (src/providers/anthropic/types.odin)
unmarshal_anthropic_usage :: proc(
	r: ^oj.Reader,
	path: string = "",
) -> (
	result: Anthropic_Usage,
	err: oj.Error,
) {
	elem, elem_err := oj.element_at(r, path)
	if elem_err != .OK do return result, elem_err
	return unmarshal_anthropic_usage_elem(r, elem)
}

// Unmarshals JSON element into Anthropic_Usage
unmarshal_anthropic_usage_elem :: proc(
	r: ^oj.Reader,
	elem: oj.Element,
) -> (
	result: Anthropic_Usage,
	err: oj.Error,
) {
	result.input_tokens, err = oj.read_int_elem(r, elem, "input_tokens")
	if err != .OK && err != .Key_Not_Found && err != .Type_Mismatch do return

	result.output_tokens, err = oj.read_int_elem(r, elem, "output_tokens")
	if err != .OK && err != .Key_Not_Found && err != .Type_Mismatch do return

	result.cache_creation_input_tokens, err = oj.read_int_elem(
		r,
		elem,
		"cache_creation_input_tokens",
	)
	if err != .OK && err != .Key_Not_Found && err != .Type_Mismatch do return

	result.cache_read_input_tokens, err = oj.read_int_elem(r, elem, "cache_read_input_tokens")
	if err != .OK && err != .Key_Not_Found && err != .Type_Mismatch do return

	return
}

is_zero_anthropic_usage :: proc(v: Anthropic_Usage) -> bool {
	return(
		v.input_tokens == 0 &&
		v.output_tokens == 0 &&
		v.cache_creation_input_tokens == 0 &&
		v.cache_read_input_tokens == 0 \
	)
}

// Marshals Anthropic_Usage to JSON
marshal_anthropic_usage :: proc(w: ^oj.Writer, value: Anthropic_Usage) {
	oj.write_object_start(w)
	oj.write_key(w, "input_tokens")
	oj.write_int(w, value.input_tokens)
	oj.write_key(w, "output_tokens")
	oj.write_int(w, value.output_tokens)
	oj.write_key(w, "cache_creation_input_tokens")
	oj.write_int(w, value.cache_creation_input_tokens)
	oj.write_key(w, "cache_read_input_tokens")
	oj.write_int(w, value.cache_read_input_tokens)
	oj.write_object_end(w)
}

// Unmarshals JSON into Anthropic_Response
// Source: anthropic (src/providers/anthropic/types.odin)
unmarshal_anthropic_response :: proc(
	r: ^oj.Reader,
	path: string = "",
) -> (
	result: Anthropic_Response,
	err: oj.Error,
) {
	elem, elem_err := oj.element_at(r, path)
	if elem_err != .OK do return result, elem_err
	return unmarshal_anthropic_response_elem(r, elem)
}

// Unmarshals JSON element into Anthropic_Response
unmarshal_anthropic_response_elem :: proc(
	r: ^oj.Reader,
	elem: oj.Element,
) -> (
	result: Anthropic_Response,
	err: oj.Error,
) {
	result.stop_reason, err = oj.read_string_elem(r, elem, "stop_reason")
	if err != .OK && err != .Key_Not_Found && err != .Type_Mismatch do return

	{
		arr_elem, arr_err := oj.obj_element_from(r, elem, "content")
		if arr_err == .OK {
			items, _ := oj.array_elements_from(r, arr_elem)
			result.content = make([]Anthropic_Content_Block, len(items))
			for item_elem, i in items {
				result.content[i], err = unmarshal_anthropic_content_block_elem(r, item_elem)
				if err != .OK do return
			}
		}
	}

	{
		nested_elem, nested_err := oj.obj_element_from(r, elem, "usage")
		if nested_err == .OK {
			result.usage, err = unmarshal_anthropic_usage_elem(r, nested_elem)
			if err != .OK do return
		}
	}

	return
}

is_zero_anthropic_response :: proc(v: Anthropic_Response) -> bool {
	return v.stop_reason == "" && len(v.content) == 0 && is_zero_anthropic_usage(v.usage)
}

// Marshals Anthropic_Response to JSON
marshal_anthropic_response :: proc(w: ^oj.Writer, value: Anthropic_Response) {
	oj.write_object_start(w)
	oj.write_key(w, "stop_reason")
	oj.write_string(w, value.stop_reason)
	oj.write_key(w, "content")
	oj.write_array_start(w)
	for item in value.content {
		marshal_anthropic_content_block(w, item)
	}
	oj.write_array_end(w)
	oj.write_key(w, "usage")
	marshal_anthropic_usage(w, value.usage)
	oj.write_object_end(w)
}
