// Code generated by ojson generator. DO NOT EDIT.
package ollama

import oj "../../../pkgs/ojson/jsonimpl"

// Unmarshals JSON into Ollama_Tool_Call_Function
// Source: ollama (src/providers/ollama/types.odin)
unmarshal_ollama_tool_call_function :: proc(r: ^oj.Reader, path: string = "") -> (result: Ollama_Tool_Call_Function, err: oj.Error) {
	elem, elem_err := oj.element_at(r, path)
	if elem_err != .OK do return result, elem_err
	return unmarshal_ollama_tool_call_function_elem(r, elem)
}

// Unmarshals JSON element into Ollama_Tool_Call_Function
unmarshal_ollama_tool_call_function_elem :: proc(r: ^oj.Reader, elem: oj.Element) -> (result: Ollama_Tool_Call_Function, err: oj.Error) {
	result.name, err = oj.read_string_elem(r, elem, "name")
	if err != .OK && err != .Key_Not_Found && err != .Type_Mismatch do return

	{
		raw_val, raw_err := oj.read_raw_elem(r, elem, "arguments")
		if raw_err != .OK && raw_err != .Key_Not_Found && raw_err != .Type_Mismatch do return result, raw_err
		if raw_err == .OK do result.arguments = raw_val
	}

	return
}

is_zero_ollama_tool_call_function :: proc(v: Ollama_Tool_Call_Function) -> bool {
	return v.name == "" && v.arguments == ""
}

// Marshals Ollama_Tool_Call_Function to JSON
marshal_ollama_tool_call_function :: proc(w: ^oj.Writer, value: Ollama_Tool_Call_Function) {
	oj.write_object_start(w)
	oj.write_key(w, "name")
	oj.write_string(w, value.name)
	oj.write_key(w, "arguments")
	oj.write_raw(w, value.arguments)
	oj.write_object_end(w)
}

// Unmarshals JSON into Ollama_Tool_Call
// Source: ollama (src/providers/ollama/types.odin)
unmarshal_ollama_tool_call :: proc(r: ^oj.Reader, path: string = "") -> (result: Ollama_Tool_Call, err: oj.Error) {
	elem, elem_err := oj.element_at(r, path)
	if elem_err != .OK do return result, elem_err
	return unmarshal_ollama_tool_call_elem(r, elem)
}

// Unmarshals JSON element into Ollama_Tool_Call
unmarshal_ollama_tool_call_elem :: proc(r: ^oj.Reader, elem: oj.Element) -> (result: Ollama_Tool_Call, err: oj.Error) {
	result.id, err = oj.read_string_elem(r, elem, "id")
	if err != .OK && err != .Key_Not_Found && err != .Type_Mismatch do return

	{
		nested_elem, nested_err := oj.obj_element_from(r, elem, "function")
		if nested_err == .OK {
			result.function, err = unmarshal_ollama_tool_call_function_elem(r, nested_elem)
			if err != .OK do return
		}
	}

	return
}

is_zero_ollama_tool_call :: proc(v: Ollama_Tool_Call) -> bool {
	return v.id == "" && is_zero_ollama_tool_call_function(v.function)
}

// Marshals Ollama_Tool_Call to JSON
marshal_ollama_tool_call :: proc(w: ^oj.Writer, value: Ollama_Tool_Call) {
	oj.write_object_start(w)
	oj.write_key(w, "id")
	oj.write_string(w, value.id)
	oj.write_key(w, "function")
	marshal_ollama_tool_call_function(w, value.function)
	oj.write_object_end(w)
}

// Unmarshals JSON into Ollama_Message
// Source: ollama (src/providers/ollama/types.odin)
unmarshal_ollama_message :: proc(r: ^oj.Reader, path: string = "") -> (result: Ollama_Message, err: oj.Error) {
	elem, elem_err := oj.element_at(r, path)
	if elem_err != .OK do return result, elem_err
	return unmarshal_ollama_message_elem(r, elem)
}

// Unmarshals JSON element into Ollama_Message
unmarshal_ollama_message_elem :: proc(r: ^oj.Reader, elem: oj.Element) -> (result: Ollama_Message, err: oj.Error) {
	result.role, err = oj.read_string_elem(r, elem, "role")
	if err != .OK && err != .Key_Not_Found && err != .Type_Mismatch do return

	result.content, err = oj.read_string_elem(r, elem, "content")
	if err != .OK && err != .Key_Not_Found && err != .Type_Mismatch do return

	result.thinking, err = oj.read_string_elem(r, elem, "thinking")
	if err != .OK && err != .Key_Not_Found && err != .Type_Mismatch do return

	{
		arr_elem, arr_err := oj.obj_element_from(r, elem, "tool_calls")
		if arr_err == .OK {
			items, _ := oj.array_elements_from(r, arr_elem)
			result.tool_calls = make([]Ollama_Tool_Call, len(items))
			for item_elem, i in items {
				result.tool_calls[i], err = unmarshal_ollama_tool_call_elem(r, item_elem)
				if err != .OK do return
			}
		}
	}

	return
}

is_zero_ollama_message :: proc(v: Ollama_Message) -> bool {
	return v.role == "" && v.content == "" && v.thinking == "" && len(v.tool_calls) == 0
}

// Marshals Ollama_Message to JSON
marshal_ollama_message :: proc(w: ^oj.Writer, value: Ollama_Message) {
	oj.write_object_start(w)
	oj.write_key(w, "role")
	oj.write_string(w, value.role)
	oj.write_key(w, "content")
	oj.write_string(w, value.content)
	if value.thinking != "" {
		oj.write_key(w, "thinking")
		oj.write_string(w, value.thinking)
	}
	if len(value.tool_calls) > 0 {
		oj.write_key(w, "tool_calls")
	oj.write_array_start(w)
	for item in value.tool_calls {
		marshal_ollama_tool_call(w, item)
	}
	oj.write_array_end(w)
	}
	oj.write_object_end(w)
}

// Unmarshals JSON into Ollama_Tool_Def_Function
// Source: ollama (src/providers/ollama/types.odin)
unmarshal_ollama_tool_def_function :: proc(r: ^oj.Reader, path: string = "") -> (result: Ollama_Tool_Def_Function, err: oj.Error) {
	elem, elem_err := oj.element_at(r, path)
	if elem_err != .OK do return result, elem_err
	return unmarshal_ollama_tool_def_function_elem(r, elem)
}

// Unmarshals JSON element into Ollama_Tool_Def_Function
unmarshal_ollama_tool_def_function_elem :: proc(r: ^oj.Reader, elem: oj.Element) -> (result: Ollama_Tool_Def_Function, err: oj.Error) {
	result.name, err = oj.read_string_elem(r, elem, "name")
	if err != .OK && err != .Key_Not_Found && err != .Type_Mismatch do return

	result.description, err = oj.read_string_elem(r, elem, "description")
	if err != .OK && err != .Key_Not_Found && err != .Type_Mismatch do return

	{
		raw_val, raw_err := oj.read_raw_elem(r, elem, "parameters")
		if raw_err != .OK && raw_err != .Key_Not_Found && raw_err != .Type_Mismatch do return result, raw_err
		if raw_err == .OK do result.parameters = raw_val
	}

	return
}

is_zero_ollama_tool_def_function :: proc(v: Ollama_Tool_Def_Function) -> bool {
	return v.name == "" && v.description == "" && v.parameters == ""
}

// Marshals Ollama_Tool_Def_Function to JSON
marshal_ollama_tool_def_function :: proc(w: ^oj.Writer, value: Ollama_Tool_Def_Function) {
	oj.write_object_start(w)
	oj.write_key(w, "name")
	oj.write_string(w, value.name)
	oj.write_key(w, "description")
	oj.write_string(w, value.description)
	oj.write_key(w, "parameters")
	oj.write_raw(w, value.parameters)
	oj.write_object_end(w)
}

// Unmarshals JSON into Ollama_Tool_Def
// Source: ollama (src/providers/ollama/types.odin)
unmarshal_ollama_tool_def :: proc(r: ^oj.Reader, path: string = "") -> (result: Ollama_Tool_Def, err: oj.Error) {
	elem, elem_err := oj.element_at(r, path)
	if elem_err != .OK do return result, elem_err
	return unmarshal_ollama_tool_def_elem(r, elem)
}

// Unmarshals JSON element into Ollama_Tool_Def
unmarshal_ollama_tool_def_elem :: proc(r: ^oj.Reader, elem: oj.Element) -> (result: Ollama_Tool_Def, err: oj.Error) {
	result.type, err = oj.read_string_elem(r, elem, "type")
	if err != .OK && err != .Key_Not_Found && err != .Type_Mismatch do return

	{
		nested_elem, nested_err := oj.obj_element_from(r, elem, "function")
		if nested_err == .OK {
			result.function, err = unmarshal_ollama_tool_def_function_elem(r, nested_elem)
			if err != .OK do return
		}
	}

	return
}

is_zero_ollama_tool_def :: proc(v: Ollama_Tool_Def) -> bool {
	return v.type == "" && is_zero_ollama_tool_def_function(v.function)
}

// Marshals Ollama_Tool_Def to JSON
marshal_ollama_tool_def :: proc(w: ^oj.Writer, value: Ollama_Tool_Def) {
	oj.write_object_start(w)
	oj.write_key(w, "type")
	oj.write_string(w, value.type)
	oj.write_key(w, "function")
	marshal_ollama_tool_def_function(w, value.function)
	oj.write_object_end(w)
}

// Unmarshals JSON into Ollama_Options
// Source: ollama (src/providers/ollama/types.odin)
unmarshal_ollama_options :: proc(r: ^oj.Reader, path: string = "") -> (result: Ollama_Options, err: oj.Error) {
	elem, elem_err := oj.element_at(r, path)
	if elem_err != .OK do return result, elem_err
	return unmarshal_ollama_options_elem(r, elem)
}

// Unmarshals JSON element into Ollama_Options
unmarshal_ollama_options_elem :: proc(r: ^oj.Reader, elem: oj.Element) -> (result: Ollama_Options, err: oj.Error) {
	result.num_ctx, err = oj.read_int_elem(r, elem, "num_ctx")
	if err != .OK && err != .Key_Not_Found && err != .Type_Mismatch do return

	{
		val: f64
		val, err = oj.read_f64_elem(r, elem, "temperature")
		if err != .OK && err != .Key_Not_Found && err != .Type_Mismatch do return
		if err == .OK do result.temperature = f32(val)
	}

	return
}

is_zero_ollama_options :: proc(v: Ollama_Options) -> bool {
	return v.num_ctx == 0 && v.temperature == 0
}

// Marshals Ollama_Options to JSON
marshal_ollama_options :: proc(w: ^oj.Writer, value: Ollama_Options) {
	oj.write_object_start(w)
	if value.num_ctx != 0 {
		oj.write_key(w, "num_ctx")
		oj.write_int(w, value.num_ctx)
	}
	if value.temperature != 0 {
		oj.write_key(w, "temperature")
		oj.write_f32(w, value.temperature)
	}
	oj.write_object_end(w)
}

// Unmarshals JSON into Ollama_Request
// Source: ollama (src/providers/ollama/types.odin)
unmarshal_ollama_request :: proc(r: ^oj.Reader, path: string = "") -> (result: Ollama_Request, err: oj.Error) {
	elem, elem_err := oj.element_at(r, path)
	if elem_err != .OK do return result, elem_err
	return unmarshal_ollama_request_elem(r, elem)
}

// Unmarshals JSON element into Ollama_Request
unmarshal_ollama_request_elem :: proc(r: ^oj.Reader, elem: oj.Element) -> (result: Ollama_Request, err: oj.Error) {
	result.model, err = oj.read_string_elem(r, elem, "model")
	if err != .OK && err != .Key_Not_Found && err != .Type_Mismatch do return

	result.stream, err = oj.read_bool_elem(r, elem, "stream")
	if err != .OK && err != .Key_Not_Found && err != .Type_Mismatch do return

	{
		raw_val, raw_err := oj.read_raw_elem(r, elem, "think")
		if raw_err != .OK && raw_err != .Key_Not_Found && raw_err != .Type_Mismatch do return result, raw_err
		if raw_err == .OK do result.think = raw_val
	}

	{
		arr_elem, arr_err := oj.obj_element_from(r, elem, "messages")
		if arr_err == .OK {
			items, _ := oj.array_elements_from(r, arr_elem)
			result.messages = make([]Ollama_Message, len(items))
			for item_elem, i in items {
				result.messages[i], err = unmarshal_ollama_message_elem(r, item_elem)
				if err != .OK do return
			}
		}
	}

	{
		arr_elem, arr_err := oj.obj_element_from(r, elem, "tools")
		if arr_err == .OK {
			items, _ := oj.array_elements_from(r, arr_elem)
			result.tools = make([]Ollama_Tool_Def, len(items))
			for item_elem, i in items {
				result.tools[i], err = unmarshal_ollama_tool_def_elem(r, item_elem)
				if err != .OK do return
			}
		}
	}

	{
		nested_elem, nested_err := oj.obj_element_from(r, elem, "options")
		if nested_err == .OK {
			result.options, err = unmarshal_ollama_options_elem(r, nested_elem)
			if err != .OK do return
		}
	}

	return
}

is_zero_ollama_request :: proc(v: Ollama_Request) -> bool {
	return v.model == "" && !v.stream && v.think == "" && len(v.messages) == 0 && len(v.tools) == 0 && is_zero_ollama_options(v.options)
}

// Marshals Ollama_Request to JSON
marshal_ollama_request :: proc(w: ^oj.Writer, value: Ollama_Request) {
	oj.write_object_start(w)
	oj.write_key(w, "model")
	oj.write_string(w, value.model)
	oj.write_key(w, "stream")
	oj.write_bool(w, value.stream)
	if value.think != "" {
		oj.write_key(w, "think")
		oj.write_raw(w, value.think)
	}
	oj.write_key(w, "messages")
	oj.write_array_start(w)
	for item in value.messages {
		marshal_ollama_message(w, item)
	}
	oj.write_array_end(w)
	if len(value.tools) > 0 {
		oj.write_key(w, "tools")
	oj.write_array_start(w)
	for item in value.tools {
		marshal_ollama_tool_def(w, item)
	}
	oj.write_array_end(w)
	}
	if !is_zero_ollama_options(value.options) {
		oj.write_key(w, "options")
		marshal_ollama_options(w, value.options)
	}
	oj.write_object_end(w)
}

// Unmarshals JSON into Ollama_Response
// Source: ollama (src/providers/ollama/types.odin)
unmarshal_ollama_response :: proc(r: ^oj.Reader, path: string = "") -> (result: Ollama_Response, err: oj.Error) {
	elem, elem_err := oj.element_at(r, path)
	if elem_err != .OK do return result, elem_err
	return unmarshal_ollama_response_elem(r, elem)
}

// Unmarshals JSON element into Ollama_Response
unmarshal_ollama_response_elem :: proc(r: ^oj.Reader, elem: oj.Element) -> (result: Ollama_Response, err: oj.Error) {
	result.done_reason, err = oj.read_string_elem(r, elem, "done_reason")
	if err != .OK && err != .Key_Not_Found && err != .Type_Mismatch do return

	{
		nested_elem, nested_err := oj.obj_element_from(r, elem, "message")
		if nested_err == .OK {
			result.message, err = unmarshal_ollama_message_elem(r, nested_elem)
			if err != .OK do return
		}
	}

	result.prompt_eval_count, err = oj.read_int_elem(r, elem, "prompt_eval_count")
	if err != .OK && err != .Key_Not_Found && err != .Type_Mismatch do return

	result.eval_count, err = oj.read_int_elem(r, elem, "eval_count")
	if err != .OK && err != .Key_Not_Found && err != .Type_Mismatch do return

	return
}

is_zero_ollama_response :: proc(v: Ollama_Response) -> bool {
	return v.done_reason == "" && is_zero_ollama_message(v.message) && v.prompt_eval_count == 0 && v.eval_count == 0
}

// Marshals Ollama_Response to JSON
marshal_ollama_response :: proc(w: ^oj.Writer, value: Ollama_Response) {
	oj.write_object_start(w)
	oj.write_key(w, "done_reason")
	oj.write_string(w, value.done_reason)
	oj.write_key(w, "message")
	marshal_ollama_message(w, value.message)
	oj.write_key(w, "prompt_eval_count")
	oj.write_int(w, value.prompt_eval_count)
	oj.write_key(w, "eval_count")
	oj.write_int(w, value.eval_count)
	oj.write_object_end(w)
}
